
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wandering_trader = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				evoker = true
				glow_squid = true
				glow_item_frame = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				tropical_fish = true
				fox = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				piglin = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				eye_of_ender = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				husk = true
				painting = true
				goat = true
				boat = true
				wither_skeleton = true
				donkey = true
				fishing_bobber = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				cave_enderman = true
				flower_fields_enderman = true
				snowy_enderman = true
				dark_oak_enderman = true
				swamp_enderman = true
				mushroom_fields_enderman = true
				badlands_enderman = true

			[light_sources.settings.entities.dragon_mounts]
				dragon = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				snowy_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				jungle_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true
				badlands_creeper = true

			[light_sources.settings.entities.deeperdarker]
				stalker = true

			[light_sources.settings.entities.hamsters]
				hamster = true

			[light_sources.settings.entities.naturalist]
				deer = true
				alligator = true
				snail = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				boar = true
				robin = true
				dragonfly = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				canary = true
				firefly = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				elephant = true
				finch = true
				lizard_tail = true

			[light_sources.settings.entities.wetlands]
				willothewisp = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				tank = true

			[light_sources.settings.entities.tacz]
				bullet = true

			[light_sources.settings.entities.dragonloot]
				dragon_trident = true

			[light_sources.settings.entities.smallships]
				galley = true
				brigg = true

			[light_sources.settings.entities.paradise_lost]
				envoy = true
				moa = true

			[light_sources.settings.entities.minecells]
				custom_arrow = true
				shockwave_placer = true

			[light_sources.settings.entities.adventurez]
				deer = true
				amethyst_golem = true
				void_shadow = true
				shaman = true
				dragon = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.dungeonnowloading]
				whimper = true
				spawner_carrier = true
				chaos_spawner = true
				hollow = true
				chaos_spawner_projectile = true
				sealed_chaos = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				ice_cube = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true
				bullet = true
				quadrocopter = true

			[light_sources.settings.entities.darkwaters]
				mohast = true
				aberration = true
				miraid = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				nightmare = true
				ghoul = true
				corrupted_pillager = true
				acolyte = true
				corrupted_vindicator = true
				wraith = true

			[light_sources.settings.entities.the_bumblezone]
				rootmin = true
				honey_slime = true
				beehemoth = true
				variant_bee = true

			[light_sources.settings.entities.tide]
				yellow_perch = true
				bluegill = true
				mint_carp = true
				bass = true
				guppy = true
				pike = true
				trout = true
				catfish = true
				clayfish = true
				fishing_bobber = true

			[light_sources.settings.entities.levelz]
				level_experience_orb = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_skeleton = true
				mutant_creeper = true
				mutant_enderman = true
				mutant_zombie = true

			[light_sources.settings.entities.knightquest]
				ratman = true
				ghosty = true
				eldbomb = true
				eldknight = true
				swampman = true

